-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-07-19 10:17:50 BRT
--   site:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ACESSO_CAIXA 
    ( 
     ID                    NUMBER (10)  NOT NULL , 
     DT_ACESSO             DATE  NOT NULL , 
     FUNCIONARIO_MATRICULA NUMBER (10)  NOT NULL , 
     CAIXA_ID              NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE ACESSO_CAIXA 
    ADD CONSTRAINT ACESSO_CAIXA_PK PRIMARY KEY ( ID ) ;

CREATE TABLE CAIXA 
    ( 
     ID              NUMBER (10)  NOT NULL , 
     PERIODO         VARCHAR2 (200 CHAR)  NOT NULL , 
     DT_PREVISAO     DATE  NOT NULL , 
     DT_ARQUIVAMENTO DATE  NOT NULL , 
     DOCUMENTO_ID    NUMBER (10)  NOT NULL , 
     STATUS_ID       NUMBER (10)  NOT NULL , 
     LOCALIZACAO_ID  NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE CAIXA 
    ADD CONSTRAINT CAIXA_PK PRIMARY KEY ( ID ) ;

CREATE TABLE DEPARTAMENTO 
    ( 
     ID   NUMBER (10)  NOT NULL , 
     NOME VARCHAR2 (200 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE DEPARTAMENTO 
    ADD CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY ( ID ) ;

CREATE TABLE DOCUMENTO 
    ( 
     ID       NUMBER (10)  NOT NULL , 
     TP_DOC   VARCHAR2 (200 CHAR)  NOT NULL , 
     TEMP_ARQ NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE DOCUMENTO 
    ADD CONSTRAINT DOCUMENTO_PK PRIMARY KEY ( ID ) ;

CREATE TABLE FUNCIONARIO 
    ( 
     MATRICULA       NUMBER (10)  NOT NULL , 
     CARGO           VARCHAR2 (200 CHAR)  NOT NULL , 
     PESSOA_ID       NUMBER (10)  NOT NULL , 
     DEPARTAMENTO_ID NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE FUNCIONARIO 
    ADD CONSTRAINT FUNCIONARIO_PK PRIMARY KEY ( MATRICULA ) ;

CREATE TABLE LOCALIZACAO 
    ( 
     ID         NUMBER (10)  NOT NULL , 
     SALA       VARCHAR2 (100 CHAR)  NOT NULL , 
     PRATELEIRA VARCHAR2 (100 CHAR)  NOT NULL , 
     COLUNA     VARCHAR2 (10 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE LOCALIZACAO 
    ADD CONSTRAINT LOCALIZACAO_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PESSOA 
    ( 
     ID   NUMBER (10)  NOT NULL , 
     NOME VARCHAR2 (250 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE PESSOA 
    ADD CONSTRAINT PESSOA_PK PRIMARY KEY ( ID ) ;

CREATE TABLE STATUS 
    ( 
     ID   NUMBER (10)  NOT NULL , 
     TIPO VARCHAR2 (200 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE STATUS 
    ADD CONSTRAINT STATUS_PK PRIMARY KEY ( ID ) ;

ALTER TABLE ACESSO_CAIXA 
    ADD CONSTRAINT ACESSO_CAIXA_CAIXA_FK FOREIGN KEY 
    ( 
     CAIXA_ID
    ) 
    REFERENCES CAIXA 
    ( 
     ID
    ) 
;

ALTER TABLE ACESSO_CAIXA 
    ADD CONSTRAINT ACESSO_CAIXA_FUNC_FK FOREIGN KEY 
    ( 
     FUNCIONARIO_MATRICULA
    ) 
    REFERENCES FUNCIONARIO 
    ( 
     MATRICULA
    ) 
;

ALTER TABLE CAIXA 
    ADD CONSTRAINT CAIXA_DOCUMENTO_FK FOREIGN KEY 
    ( 
     DOCUMENTO_ID
    ) 
    REFERENCES DOCUMENTO 
    ( 
     ID
    ) 
;

ALTER TABLE CAIXA 
    ADD CONSTRAINT CAIXA_LOCALIZACAO_FK FOREIGN KEY 
    ( 
     LOCALIZACAO_ID
    ) 
    REFERENCES LOCALIZACAO 
    ( 
     ID
    ) 
;

ALTER TABLE CAIXA 
    ADD CONSTRAINT CAIXA_STATUS_FK FOREIGN KEY 
    ( 
     STATUS_ID
    ) 
    REFERENCES STATUS 
    ( 
     ID
    ) 
;

ALTER TABLE FUNCIONARIO 
    ADD CONSTRAINT FUNC_DEP_FK FOREIGN KEY 
    ( 
     DEPARTAMENTO_ID
    ) 
    REFERENCES DEPARTAMENTO 
    ( 
     ID
    ) 
;

ALTER TABLE FUNCIONARIO 
    ADD CONSTRAINT FUNC_PESSOA_FK FOREIGN KEY 
    ( 
     PESSOA_ID
    ) 
    REFERENCES PESSOA 
    ( 
     ID
    ) 
;

CREATE SEQUENCE ACESSO_CAIXA_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER ACESSO_CAIXA_ID_TRG 
BEFORE INSERT ON ACESSO_CAIXA 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    :NEW.ID := ACESSO_CAIXA_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE CAIXA_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER CAIXA_ID_TRG 
BEFORE INSERT ON CAIXA 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    :NEW.ID := CAIXA_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE DEPARTAMENTO_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER DEPARTAMENTO_ID_TRG 
BEFORE INSERT ON DEPARTAMENTO 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    :NEW.ID := DEPARTAMENTO_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE DOCUMENTO_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER DOCUMENTO_ID_TRG 
BEFORE INSERT ON DOCUMENTO 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    :NEW.ID := DOCUMENTO_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE FUNCIONARIO_MATRICULA_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER FUNCIONARIO_MATRICULA_TRG 
BEFORE INSERT ON FUNCIONARIO 
FOR EACH ROW 
WHEN (NEW.MATRICULA IS NULL) 
BEGIN 
    :NEW.MATRICULA := FUNCIONARIO_MATRICULA_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE LOCALIZACAO_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER LOCALIZACAO_ID_TRG 
BEFORE INSERT ON LOCALIZACAO 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    :NEW.ID := LOCALIZACAO_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE PESSOA_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER PESSOA_ID_TRG 
BEFORE INSERT ON PESSOA 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    :NEW.ID := PESSOA_ID_SEQ.NEXTVAL; 
END;
/

CREATE SEQUENCE STATUS_ID_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER STATUS_ID_TRG 
BEFORE INSERT ON STATUS 
FOR EACH ROW 
WHEN (NEW.ID IS NULL) 
BEGIN 
    :NEW.ID := STATUS_ID_SEQ.NEXTVAL; 
END;
/



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           8
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          8
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
